export const work = [
  {
    name: 'solbound',
    timeline: '2023 - present',
    projects: [
      {
        name: 'The Heist',
        description:
          'A high-stakes, risk-based game of crime, corruption...and bananas. Idle web game built on the Solana Blockchain.',
        tech: [
          'TypeScript',
          'React',
          'Nestjs',
          'PostgreSQL',
          'AWS',
          'Terraform',
          'Ansible',
          'Docker',
          'GitHub Actions',
          'Metaplex',
          'Solana',
        ],
        web: 'https://theheist.game/',
        img: '/img/theheist.png',
      },
      {
        name: 'The Remnants',
        description: 'Mobile idle game built on the Solana Blockchain.',
        tech: [
          'TypeScript',
          'React',
          'Nestjs',
          'PostgreSQL',
          'AWS',
          'Terraform',
          'Ansible',
          'Docker',
          'GitHub Actions',
        ],
        web: 'https://theremnants.app/',
        img: '/img/theremnants.png',
      },
      {
        name: 'solana_wallet_exporter',
        description: 'Prometheus exporter for Solana wallet SOL and token balance',
        tech: ['Go', 'Docker', 'GitHub Actions', 'Solana'],
        src: 'https://github.com/solbound-dev/solana_wallet_exporter',
      },
    ],
  },
  {
    name: 'ExtensionEngine',
    web: 'https://extensionengine.com/',
    timeline: '2022',
    projects: [
      {
        name: 'rasporedar',
        description: 'School timetable generator web application',
        src: 'https://github.com/ExtensionEngine/rasporedar',
        img: '/img/rasporedar.png',
        tech: ['TypeScript', 'Vue', 'Express.js', 'PostgreSQL', 'Docker'],
      },
    ],
  },
];

export const nonprofits = [
  {
    name: 'DUMP',
    web: 'https://dump.hr/',
    timeline: '2022 - present',
    projects: [
      {
        name: 'DUMP Days 2024 App',
        description: 'DUMP Days 2024 conference companion app',
        web: 'https://days.dump.hr/',
        src: 'https://github.com/dump-hr/ddays-app',
        tech: [
          'TypeScript',
          'React',
          'Nestjs',
          'PostgreSQL',
          'Drizzle',
          'AWS',
          'Terraform',
          'Ansible',
          'Docker',
        ],
      },
      {
        name: 'DUMP Internship App',
        description: 'Web app for managing DUMP Internship applications',
        web: 'https://internship.dump.hr/',
        src: 'https://github.com/dump-hr/internship-app',
        img: '/img/internship-app.png',
        tech: [
          'TypeScript',
          'React',
          'Nestjs',
          'PostgreSQL',
          'Prisma',
          'AWS',
          'Terraform',
          'Ansible',
          'Docker',
        ],
      },
      {
        name: 'Studentski Poslovi',
        description: 'Student-Employer matching app for SC Split',
        img: '/img/studentski-poslovi.png',
        tech: ['TypeScript', 'React', 'Nestjs', 'PostgreSQL', 'Prisma', 'Docker'],
      },
      {
        name: 'SafetyNet',
        description: 'Quiz about internet security',
        web: 'https://safetynet-kviz.skole.hr/',
        src: 'https://github.com/dump-hr/safetynet',
        img: '/img/safetynet.png',
        tech: [
          'TypeScript',
          'React',
          'Nestjs',
          'PostgreSQL',
          'Prisma',
          'AWS',
          'Terraform',
          'Ansible',
          'Docker',
        ],
      },
      {
        name: 'DUMP Days 2023 App',
        description: 'DUMP Days 2023 conference companion app',
        web: 'https://2023.days.dump.hr/',
        img: '/img/ddays-app-2023.png',
        imgbrightness: 0.4,
        tech: [
          'TypeScript',
          'React',
          'C#',
          'EF Core',
          'PostgreSQL',
          'Azure',
          'Terraform',
          'Ansible',
          'Docker',
        ],
      },
    ],
  },
  {
    name: 'DUMP Internship',
    web: 'https://dump.hr/internship',
    timeline: '2021 - 2022',
    projects: [
      {
        name: 'Ludo',
        tech: ['React', 'JavaScript', 'AWS'],
        web: 'https://ludo.bdeak.net',
        src: 'https://github.com/bdeak4/Internship-18-Ludo',
        img: '/img/ludo.png',
      },
      {
        name: 'PostsAndComments',
        description: 'Forum web app',
        tech: ['JavaScript', 'CSS Animations', 'AWS'],
        web: 'https://postsandcomments.bdeak.net',
        src: 'https://github.com/bdeak4/Internship-14-PostsAndComments',
        img: '/img/postsandcomments.png',
      },
    ],
  },
];

export const projects = [
  {
    name: 'chatter',
    description: 'cryptocurrency online mentions analyzer web app',
    web: 'https://chatter.exposed/',
    src: 'https://github.com/bdeak4/chatter',
    img: '/img/chatter.png',
    imgbrightness: 0.4,
    tech: ['Python', 'Flask', 'TextBlob', 'PostgreSQL', 'Redis', 'Docker'],
  },
  {
    name: 'stack.management',
    description: 'low distraction todo app that helps you prioritize and focus',
    web: 'https://stack.management/',
    src: 'https://github.com/bdeak4/stack.management',
    img: '/img/stack-management.png',
    imgbrightness: 0.4,
    tech: ['TypeScript', 'React', 'Nestjs', 'PostgreSQL', 'Prisma', 'Docker'],
  },
  {
    name: 'generate-nft-assets',
    description: 'generate nft metaplex sugar assets from trait images',
    src: 'https://github.com/bdeak4/generate-nft-assets',
    tech: ['TypeScript', 'Solana', 'Metaplex'],
  },
  {
    name: 'raid5-seed-phrase',
    description: 'Protect your crypto seed phrase with the power of RAID5',
    src: 'https://github.com/bdeak4/raid5-seed-phrase',
    tech: ['JavaScript'],
  },
  {
    name: 'react-animated-list',
    description: 'React component for animating list changes',
    src: 'https://github.com/bdeak4/react-animated-list',
    img: '/img/react-animated-list.gif',
    tech: ['React', 'TypeScript'],
  },
  {
    name: 'github-mirror',
    description: 'Mirror your GitHub repositories using cgit',
    src: 'https://github.com/bdeak4/github-mirror',
    img: '/img/github-mirror.png',
    tech: ['Bash', 'Docker', 'Nginx'],
  },
];
